package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditNote generated by hbm2java
 */
@Entity
@Table(name="credit_note"
    ,catalog="creative_edge"
)
public class CreditNote  implements java.io.Serializable {


     private Long crnNo;
     private Invoice invoice;
     private User user;
     private Date date;
     private String remarks;
     private double total;
     private Set<CreditNoteLine> creditNoteLines = new HashSet<CreditNoteLine>(0);

    public CreditNote() {
    }

	
    public CreditNote(Invoice invoice, User user, Date date, String remarks, double total) {
        this.invoice = invoice;
        this.user = user;
        this.date = date;
        this.remarks = remarks;
        this.total = total;
    }
    public CreditNote(Invoice invoice, User user, Date date, String remarks, double total, Set<CreditNoteLine> creditNoteLines) {
       this.invoice = invoice;
       this.user = user;
       this.date = date;
       this.remarks = remarks;
       this.total = total;
       this.creditNoteLines = creditNoteLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="crn_no", unique=true, nullable=false)
    public Long getCrnNo() {
        return this.crnNo;
    }
    
    public void setCrnNo(Long crnNo) {
        this.crnNo = crnNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inv_no", nullable=false)
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="remarks", nullable=false)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="total", nullable=false, precision=10)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="creditNote")
    public Set<CreditNoteLine> getCreditNoteLines() {
        return this.creditNoteLines;
    }
    
    public void setCreditNoteLines(Set<CreditNoteLine> creditNoteLines) {
        this.creditNoteLines = creditNoteLines;
    }




}


