package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CreditNoteLine generated by hbm2java
 */
@Entity
@Table(name="credit_note_line"
    ,catalog="creative_edge"
)
public class CreditNoteLine  implements java.io.Serializable {


     private long id;
     private CreditNote creditNote;
     private FinishedItem finishedItem;
     private double qty;
     private double price;

    public CreditNoteLine() {
    }

    public CreditNoteLine(long id, CreditNote creditNote, FinishedItem finishedItem, double qty, double price) {
       this.id = id;
       this.creditNote = creditNote;
       this.finishedItem = finishedItem;
       this.qty = qty;
       this.price = price;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="crn_no", nullable=false)
    public CreditNote getCreditNote() {
        return this.creditNote;
    }
    
    public void setCreditNote(CreditNote creditNote) {
        this.creditNote = creditNote;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public FinishedItem getFinishedItem() {
        return this.finishedItem;
    }
    
    public void setFinishedItem(FinishedItem finishedItem) {
        this.finishedItem = finishedItem;
    }

    
    @Column(name="qty", nullable=false, precision=10)
    public double getQty() {
        return this.qty;
    }
    
    public void setQty(double qty) {
        this.qty = qty;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


