package com.kn.ce.model.entity;
// Generated Oct 29, 2016 2:42:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerTransaction generated by hbm2java
 */
@Entity
@Table(name="customer_transaction"
    ,catalog="creative_edge"
)
public class CustomerTransaction  implements java.io.Serializable {


     private Long id;
     private Customer customer;
     private Invoice invoice;
     private Date date;
     private String type;
     private double amount;
     private Long refNo;

    public CustomerTransaction() {
    }

	
    public CustomerTransaction(Customer customer, Invoice invoice, Date date, String type, double amount) {
        this.customer = customer;
        this.invoice = invoice;
        this.date = date;
        this.type = type;
        this.amount = amount;
    }
    public CustomerTransaction(Customer customer, Invoice invoice, Date date, String type, double amount, Long refNo) {
       this.customer = customer;
       this.invoice = invoice;
       this.date = date;
       this.type = type;
       this.amount = amount;
       this.refNo = refNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cust_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inv_no", nullable=false)
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="type", nullable=false, length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="ref_no")
    public Long getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(Long refNo) {
        this.refNo = refNo;
    }




}


