package com.kn.ce.model.entity;
// Generated Oct 17, 2016 9:55:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GrnLine generated by hbm2java
 */
@Entity
@Table(name="grn_line"
    ,catalog="creative_edge"
)
public class GrnLine  implements java.io.Serializable {


     private Long id;
     private Grn grn;
     private RawItem rawItem;
     private double qty;
     private double price;

    public GrnLine() {
    }

    public GrnLine(Grn grn, RawItem rawItem, double qty, double price) {
       this.grn = grn;
       this.rawItem = rawItem;
       this.qty = qty;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grn_id", nullable=false)
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public RawItem getRawItem() {
        return this.rawItem;
    }
    
    public void setRawItem(RawItem rawItem) {
        this.rawItem = rawItem;
    }

    
    @Column(name="qty", nullable=false, precision=10)
    public double getQty() {
        return this.qty;
    }
    
    public void setQty(double qty) {
        this.qty = qty;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


