package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrnPayment generated by hbm2java
 */
@Entity
@Table(name="grn_payment"
    ,catalog="creative_edge"
)
public class GrnPayment  implements java.io.Serializable {


     private long id;
     private Grn grn;
     private User user;
     private Date date;
     private String payType;
     private double amount;
     private String refNo;

    public GrnPayment() {
    }

	
    public GrnPayment(long id, Grn grn, User user, Date date, String payType, double amount) {
        this.id = id;
        this.grn = grn;
        this.user = user;
        this.date = date;
        this.payType = payType;
        this.amount = amount;
    }
    public GrnPayment(long id, Grn grn, User user, Date date, String payType, double amount, String refNo) {
       this.id = id;
       this.grn = grn;
       this.user = user;
       this.date = date;
       this.payType = payType;
       this.amount = amount;
       this.refNo = refNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grn_no", nullable=false)
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="pay_type", nullable=false, length=10)
    public String getPayType() {
        return this.payType;
    }
    
    public void setPayType(String payType) {
        this.payType = payType;
    }

    
    @Column(name="amount", nullable=false, precision=20)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="ref_no", length=10)
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }




}


