package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrnReturn generated by hbm2java
 */
@Entity
@Table(name="grn_return"
    ,catalog="creative_edge"
)
public class GrnReturn  implements java.io.Serializable {


     private Long rtnNo;
     private Grn grn;
     private User user;
     private Date date;
     private String remarks;
     private double total;
     private Set<GrnReturnLine> grnReturnLines = new HashSet<GrnReturnLine>(0);

    public GrnReturn() {
    }

	
    public GrnReturn(Grn grn, User user, Date date, String remarks, double total) {
        this.grn = grn;
        this.user = user;
        this.date = date;
        this.remarks = remarks;
        this.total = total;
    }
    public GrnReturn(Grn grn, User user, Date date, String remarks, double total, Set<GrnReturnLine> grnReturnLines) {
       this.grn = grn;
       this.user = user;
       this.date = date;
       this.remarks = remarks;
       this.total = total;
       this.grnReturnLines = grnReturnLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rtn_no", unique=true, nullable=false)
    public Long getRtnNo() {
        return this.rtnNo;
    }
    
    public void setRtnNo(Long rtnNo) {
        this.rtnNo = rtnNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grn_no", nullable=false)
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="remarks", nullable=false)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="total", nullable=false, precision=10)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grnReturn")
    public Set<GrnReturnLine> getGrnReturnLines() {
        return this.grnReturnLines;
    }
    
    public void setGrnReturnLines(Set<GrnReturnLine> grnReturnLines) {
        this.grnReturnLines = grnReturnLines;
    }




}


