package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvoiceLine generated by hbm2java
 */
@Entity
@Table(name="invoice_line"
    ,catalog="creative_edge"
)
public class InvoiceLine  implements java.io.Serializable {


     private long id;
     private FinishedItem finishedItem;
     private Invoice invoice;
     private double qty;
     private double unitPrice;
     private double width;
     private double height;
    

    public InvoiceLine() {
    }

	
    public InvoiceLine(long id, FinishedItem finishedItem, Invoice invoice, double qty, double unitPrice, double width, double height) {
        this.id = id;
        this.finishedItem = finishedItem;
        this.invoice = invoice;
        this.qty = qty;
        this.unitPrice = unitPrice;
        this.width = width;
        this.height = height;
    }
   
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public FinishedItem getFinishedItem() {
        return this.finishedItem;
    }
    
    public void setFinishedItem(FinishedItem finishedItem) {
        this.finishedItem = finishedItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inv_id", nullable=false)
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    
    @Column(name="qty", nullable=false, precision=10)
    public double getQty() {
        return this.qty;
    }
    
    public void setQty(double qty) {
        this.qty = qty;
    }

    
    @Column(name="unit_price", nullable=false, precision=10)
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="width", nullable=false, precision=5)
    public double getWidth() {
        return this.width;
    }
    
    public void setWidth(double width) {
        this.width = width;
    }

    
    @Column(name="height", nullable=false, precision=5)
    public double getHeight() {
        return this.height;
    }
    
    public void setHeight(double height) {
        this.height = height;
    }

    
 




}


