package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobLine generated by hbm2java
 */
@Entity
@Table(name="job_line"
    ,catalog="creative_edge"
)
public class JobLine  implements java.io.Serializable {


     private Long id;
     private FinishedItem finishedItem;
     private Job job;
     private double unitPrice;
     private int qty;
     private double width;
     private double height;
     private String remarks;

    public JobLine() {
    }

	
    public JobLine(FinishedItem finishedItem, Job job, double unitPrice, int qty, double width, double height) {
        this.finishedItem = finishedItem;
        this.job = job;
        this.unitPrice = unitPrice;
        this.qty = qty;
        this.width = width;
        this.height = height;
    }
    public JobLine(FinishedItem finishedItem, Job job, double unitPrice, int qty, double width, double height, String remarks) {
       this.finishedItem = finishedItem;
       this.job = job;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.width = width;
       this.height = height;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public FinishedItem getFinishedItem() {
        return this.finishedItem;
    }
    
    public void setFinishedItem(FinishedItem finishedItem) {
        this.finishedItem = finishedItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_no", nullable=false)
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }

    
    @Column(name="unit_price", nullable=false, precision=10)
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="width", nullable=false, precision=5)
    public double getWidth() {
        return this.width;
    }
    
    public void setWidth(double width) {
        this.width = width;
    }

    
    @Column(name="height", nullable=false, precision=5)
    public double getHeight() {
        return this.height;
    }
    
    public void setHeight(double height) {
        this.height = height;
    }

    
    @Column(name="remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


