package com.kn.ce.model.entity;
// Generated Oct 1, 2016 1:28:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawItemIssueRtn generated by hbm2java
 */
@Entity
@Table(name="raw_item_issue_rtn"
    ,catalog="creative_edge"
)
public class RawItemIssueRtn  implements java.io.Serializable {


     private Long rtnNo;
     private RawItemIssue rawItemIssue;
     private User user;
     private Date date;
     private String remarks;
     private Set<RawItemIssueRtnLine> rawItemIssueRtnLines = new HashSet<RawItemIssueRtnLine>(0);

    public RawItemIssueRtn() {
    }

	
    public RawItemIssueRtn(RawItemIssue rawItemIssue, User user, Date date, String remarks) {
        this.rawItemIssue = rawItemIssue;
        this.user = user;
        this.date = date;
        this.remarks = remarks;
    }
    public RawItemIssueRtn(RawItemIssue rawItemIssue, User user, Date date, String remarks, Set<RawItemIssueRtnLine> rawItemIssueRtnLines) {
       this.rawItemIssue = rawItemIssue;
       this.user = user;
       this.date = date;
       this.remarks = remarks;
       this.rawItemIssueRtnLines = rawItemIssueRtnLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rtn_no", unique=true, nullable=false)
    public Long getRtnNo() {
        return this.rtnNo;
    }
    
    public void setRtnNo(Long rtnNo) {
        this.rtnNo = rtnNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="issue_no", nullable=false)
    public RawItemIssue getRawItemIssue() {
        return this.rawItemIssue;
    }
    
    public void setRawItemIssue(RawItemIssue rawItemIssue) {
        this.rawItemIssue = rawItemIssue;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="remarks", nullable=false)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItemIssueRtn")
    public Set<RawItemIssueRtnLine> getRawItemIssueRtnLines() {
        return this.rawItemIssueRtnLines;
    }
    
    public void setRawItemIssueRtnLines(Set<RawItemIssueRtnLine> rawItemIssueRtnLines) {
        this.rawItemIssueRtnLines = rawItemIssueRtnLines;
    }




}


