package com.kn.ce.model.entity;
// Generated Oct 1, 2016 1:28:38 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RawItemIssueRtnLine generated by hbm2java
 */
@Entity
@Table(name="raw_item_issue_rtn_line"
    ,catalog="creative_edge"
)
public class RawItemIssueRtnLine  implements java.io.Serializable {


     private Long id;
     private RawItem rawItem;
     private RawItemIssueRtn rawItemIssueRtn;
     private double qty;

    public RawItemIssueRtnLine() {
    }

    public RawItemIssueRtnLine(RawItem rawItem, RawItemIssueRtn rawItemIssueRtn, double qty) {
       this.rawItem = rawItem;
       this.rawItemIssueRtn = rawItemIssueRtn;
       this.qty = qty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false)
    public RawItem getRawItem() {
        return this.rawItem;
    }
    
    public void setRawItem(RawItem rawItem) {
        this.rawItem = rawItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rtn_id", nullable=false)
    public RawItemIssueRtn getRawItemIssueRtn() {
        return this.rawItemIssueRtn;
    }
    
    public void setRawItemIssueRtn(RawItemIssueRtn rawItemIssueRtn) {
        this.rawItemIssueRtn = rawItemIssueRtn;
    }

    
    @Column(name="qty", nullable=false, precision=10)
    public double getQty() {
        return this.qty;
    }
    
    public void setQty(double qty) {
        this.qty = qty;
    }




}


