package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawItemIssue generated by hbm2java
 */
@Entity
@Table(name="raw_item_issue"
    ,catalog="creative_edge"
)
public class RawItemIssue  implements java.io.Serializable {


     private Long issueNo;
     private Job job;
     private User user;
     private Worker worker;
     private Date date;
     private String remarks;
     private Set<RawItemIssueLine> rawItemIssueLines = new HashSet<RawItemIssueLine>(0);

    public RawItemIssue() {
    }

	
    public RawItemIssue(Job job, User user, Worker worker, Date date, String remarks) {
        this.job = job;
        this.user = user;
        this.worker = worker;
        this.date = date;
        this.remarks = remarks;
    }
    public RawItemIssue(Job job, User user, Worker worker, Date date, String remarks, Set<RawItemIssueLine> rawItemIssueLines) {
       this.job = job;
       this.user = user;
       this.worker = worker;
       this.date = date;
       this.remarks = remarks;
       this.rawItemIssueLines = rawItemIssueLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="issue_no", unique=true, nullable=false)
    public Long getIssueNo() {
        return this.issueNo;
    }
    
    public void setIssueNo(Long issueNo) {
        this.issueNo = issueNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_no", nullable=false)
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="issue_to", nullable=false)
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="remarks", nullable=false)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItemIssue")
    public Set<RawItemIssueLine> getRawItemIssueLines() {
        return this.rawItemIssueLines;
    }
    
    public void setRawItemIssueLines(Set<RawItemIssueLine> rawItemIssueLines) {
        this.rawItemIssueLines = rawItemIssueLines;
    }




}


