package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RawItemCategory generated by hbm2java
 */
@Entity
@Table(name="raw_item_category"
    ,catalog="creative_edge"
)
public class RawItemCategory  implements java.io.Serializable {


     private String category;
     private Set<RawItem> rawItems = new HashSet<RawItem>(0);

    public RawItemCategory() {
    }

	
    public RawItemCategory(String category) {
        this.category = category;
    }
    public RawItemCategory(String category, Set<RawItem> rawItems) {
       this.category = category;
       this.rawItems = rawItems;
    }
   
     @Id 

    
    @Column(name="category", unique=true, nullable=false, length=50)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItemCategory")
    public Set<RawItem> getRawItems() {
        return this.rawItems;
    }
    
    public void setRawItems(Set<RawItem> rawItems) {
        this.rawItems = rawItems;
    }




}


