package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RawItem generated by hbm2java
 */
@Entity
@Table(name="raw_item"
    ,catalog="creative_edge"
)
public class RawItem  implements java.io.Serializable {


     private Long itemId;
     private RawItemCategory rawItemCategory;
     private Uom uom;
     private String description;
     private double cost;
     private String remarks;
     private double reorderLevel;
     private Set<GrnLine> grnLines = new HashSet<GrnLine>(0);
     private Set<RawItemIssueLine> rawItemIssueLines = new HashSet<RawItemIssueLine>(0);
     private Set<RawItemStock> rawItemStocks = new HashSet<RawItemStock>(0);
     private Set<GrnReturnLine> grnReturnLines = new HashSet<GrnReturnLine>(0);
     
     //calculation fields
     private Double StockQty;

    public RawItem() {
    }

	
    public RawItem(RawItemCategory rawItemCategory, Uom uom, String description, double cost, double reorderLevel) {
        this.rawItemCategory = rawItemCategory;
        this.uom = uom;
        this.description = description;
        this.cost = cost;
        this.reorderLevel = reorderLevel;
    }
    public RawItem(RawItemCategory rawItemCategory, Uom uom, String description, double cost, String remarks, double reorderLevel, Set<GrnLine> grnLines, Set<RawItemIssueLine> rawItemIssueLines, Set<RawItemStock> rawItemStocks, Set<GrnReturnLine> grnReturnLines) {
       this.rawItemCategory = rawItemCategory;
       this.uom = uom;
       this.description = description;
       this.cost = cost;
       this.remarks = remarks;
       this.reorderLevel = reorderLevel;
       this.grnLines = grnLines;
       this.rawItemIssueLines = rawItemIssueLines;
       this.rawItemStocks = rawItemStocks;
       this.grnReturnLines = grnReturnLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="item_id", unique=true, nullable=false)
    public Long getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category", nullable=false)
    public RawItemCategory getRawItemCategory() {
        return this.rawItemCategory;
    }
    
    public void setRawItemCategory(RawItemCategory rawItemCategory) {
        this.rawItemCategory = rawItemCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uom", nullable=false)
    public Uom getUom() {
        return this.uom;
    }
    
    public void setUom(Uom uom) {
        this.uom = uom;
    }

    
    @Column(name="description", nullable=false, length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="cost", nullable=false, precision=10)
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }

    
    @Column(name="remarks")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="reorder_level", nullable=false, precision=5)
    public double getReorderLevel() {
        return this.reorderLevel;
    }
    
    public void setReorderLevel(double reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItem")
    public Set<GrnLine> getGrnLines() {
        return this.grnLines;
    }
    
    public void setGrnLines(Set<GrnLine> grnLines) {
        this.grnLines = grnLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItem")
    public Set<RawItemIssueLine> getRawItemIssueLines() {
        return this.rawItemIssueLines;
    }
    
    public void setRawItemIssueLines(Set<RawItemIssueLine> rawItemIssueLines) {
        this.rawItemIssueLines = rawItemIssueLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItem")
    public Set<RawItemStock> getRawItemStocks() {
        return this.rawItemStocks;
    }
    
    public void setRawItemStocks(Set<RawItemStock> rawItemStocks) {
        this.rawItemStocks = rawItemStocks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rawItem")
    public Set<GrnReturnLine> getGrnReturnLines() {
        return this.grnReturnLines;
    }
    
    public void setGrnReturnLines(Set<GrnReturnLine> grnReturnLines) {
        this.grnReturnLines = grnReturnLines;
    }

    @Transient
    public Double getStockQty() {
        return StockQty;
    }

    public void setStockQty(Double StockQty) {
        this.StockQty = StockQty;
    }

    



}


