package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="creative_edge"
)
public class Supplier  implements java.io.Serializable {


     private Long supId;
     private String name;
     private String address1;
     private String address2;
     private String city;
     private String postalCode;
     private String tel1;
     private String tel2;
     private String fax;
     private String cperson;
     private String mobile;
     private String email;
     private String remarks;
     private Set<SupplierTransaction> supplierTransactions = new HashSet<SupplierTransaction>(0);
     private Set<Grn> grns = new HashSet<Grn>(0);

    public Supplier() {
    }

	
    public Supplier(String name, String address1, String address2, String tel1) {
        this.name = name;
        this.address1 = address1;
        this.address2 = address2;
        this.tel1 = tel1;
    }
    public Supplier(String name, String address1, String address2, String city, String postalCode, String tel1, String tel2, String fax, String cperson, String mobile, String email, String remarks, Set<SupplierTransaction> supplierTransactions, Set<Grn> grns) {
       this.name = name;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.postalCode = postalCode;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.fax = fax;
       this.cperson = cperson;
       this.mobile = mobile;
       this.email = email;
       this.remarks = remarks;
       this.supplierTransactions = supplierTransactions;
       this.grns = grns;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sup_id", unique=true, nullable=false)
    public Long getSupId() {
        return this.supId;
    }
    
    public void setSupId(Long supId) {
        this.supId = supId;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address1", nullable=false)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="address2", nullable=false)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="postal_code", length=50)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="tel1", nullable=false, length=15)
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }

    
    @Column(name="tel2", length=15)
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }

    
    @Column(name="fax", length=50)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="cperson", length=50)
    public String getCperson() {
        return this.cperson;
    }
    
    public void setCperson(String cperson) {
        this.cperson = cperson;
    }

    
    @Column(name="mobile", length=15)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="remarks", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<SupplierTransaction> getSupplierTransactions() {
        return this.supplierTransactions;
    }
    
    public void setSupplierTransactions(Set<SupplierTransaction> supplierTransactions) {
        this.supplierTransactions = supplierTransactions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplier")
    public Set<Grn> getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set<Grn> grns) {
        this.grns = grns;
    }




}


