package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierTransaction generated by hbm2java
 */
@Entity
@Table(name="supplier_transaction"
    ,catalog="creative_edge"
)
public class SupplierTransaction  implements java.io.Serializable {


     private Long id;
     private Supplier supplier;
     private Grn grn;
     private Date date;
     private long refNo;
     private String type;
     private double amount;

    public SupplierTransaction() {
    }

        public SupplierTransaction(Supplier supplier,Grn grn, Date date,String type, double amount) {
       this.supplier = supplier;
       this.grn=grn;
       this.date = date;   
       this.type = type;
       this.amount = amount;
    }
    public SupplierTransaction(Supplier supplier,Grn grn,Date date, long refNo, String type, double amount) {
       this.supplier = supplier;
       this.grn=grn;
       this.date = date;
       this.refNo = refNo;
       this.type = type;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sup_id", nullable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="ref_no")
    public long getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(long refNo) {
        this.refNo = refNo;
    }

    
    @Column(name="type", nullable=false, length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="amount", nullable=false, precision=10)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    public void setGrn(Grn grn) {
        this.grn = grn;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grn_no", nullable=false)
    public Grn getGrn() {
        return grn;
    }
    
    




}


