package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemPage generated by hbm2java
 */
@Entity
@Table(name="system_page"
    ,catalog="creative_edge"
)
public class SystemPage  implements java.io.Serializable {


     private Integer id;
     private String pageName;
     private String url;
     private String icon;
     private String catergory;
     private Set<UserPageAccess> userPageAccesses = new HashSet<UserPageAccess>(0);

    public SystemPage() {
    }

	
    public SystemPage(String pageName, String url, String icon, String catergory) {
        this.pageName = pageName;
        this.url = url;
        this.icon = icon;
        this.catergory = catergory;
    }
    public SystemPage(String pageName, String url, String icon, String catergory, Set<UserPageAccess> userPageAccesses) {
       this.pageName = pageName;
       this.url = url;
       this.icon = icon;
       this.catergory = catergory;
       this.userPageAccesses = userPageAccesses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="page_name", nullable=false)
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="icon", nullable=false, length=50)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

    
    @Column(name="catergory", nullable=false, length=50)
    public String getCatergory() {
        return this.catergory;
    }
    
    public void setCatergory(String catergory) {
        this.catergory = catergory;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="systemPage")
    public Set<UserPageAccess> getUserPageAccesses() {
        return this.userPageAccesses;
    }
    
    public void setUserPageAccesses(Set<UserPageAccess> userPageAccesses) {
        this.userPageAccesses = userPageAccesses;
    }




}


