package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserPageAccessId generated by hbm2java
 */
@Embeddable
public class UserPageAccessId  implements java.io.Serializable {


     private int pageId;
     private String userRole;

    public UserPageAccessId() {
    }

    public UserPageAccessId(int pageId, String userRole) {
       this.pageId = pageId;
       this.userRole = userRole;
    }
   


    @Column(name="page_id", nullable=false)
    public int getPageId() {
        return this.pageId;
    }
    
    public void setPageId(int pageId) {
        this.pageId = pageId;
    }


    @Column(name="user_role", nullable=false, length=20)
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserPageAccessId) ) return false;
		 UserPageAccessId castOther = ( UserPageAccessId ) other; 
         
		 return (this.getPageId()==castOther.getPageId())
 && ( (this.getUserRole()==castOther.getUserRole()) || ( this.getUserRole()!=null && castOther.getUserRole()!=null && this.getUserRole().equals(castOther.getUserRole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPageId();
         result = 37 * result + ( getUserRole() == null ? 0 : this.getUserRole().hashCode() );
         return result;
   }   


}


