package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="user_role"
    ,catalog="creative_edge"
)
public class UserRole  implements java.io.Serializable {


     private String userRole;
     private Set<UserPageAccess> userPageAccesses = new HashSet<UserPageAccess>(0);
     private Set<User> users = new HashSet<User>(0);

    public UserRole() {
    }

	
    public UserRole(String userRole) {
        this.userRole = userRole;
    }
    public UserRole(String userRole, Set<UserPageAccess> userPageAccesses, Set<User> users) {
       this.userRole = userRole;
       this.userPageAccesses = userPageAccesses;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="user_role", unique=true, nullable=false, length=20)
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userRole")
    public Set<UserPageAccess> getUserPageAccesses() {
        return this.userPageAccesses;
    }
    
    public void setUserPageAccesses(Set<UserPageAccess> userPageAccesses) {
        this.userPageAccesses = userPageAccesses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userRole")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


