package com.kn.ce.model.entity;
// Generated Oct 1, 2016 10:00:22 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserPageAccess generated by hbm2java
 */
@Entity
@Table(name="user_page_access"
    ,catalog="creative_edge"
)
public class UserPageAccess  implements java.io.Serializable {


     private UserPageAccessId id;
     private SystemPage systemPage;
     private UserRole userRole;
     private boolean access;

    public UserPageAccess() {
    }

    public UserPageAccess(UserPageAccessId id, SystemPage systemPage, UserRole userRole, boolean access) {
       this.id = id;
       this.systemPage = systemPage;
       this.userRole = userRole;
       this.access = access;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pageId", column=@Column(name="page_id", nullable=false) ), 
        @AttributeOverride(name="userRole", column=@Column(name="user_role", nullable=false, length=20) ) } )
    public UserPageAccessId getId() {
        return this.id;
    }
    
    public void setId(UserPageAccessId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="page_id", nullable=false, insertable=false, updatable=false)
    public SystemPage getSystemPage() {
        return this.systemPage;
    }
    
    public void setSystemPage(SystemPage systemPage) {
        this.systemPage = systemPage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_role", nullable=false, insertable=false, updatable=false)
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

    
    @Column(name="access", nullable=false)
    public boolean isAccess() {
        return this.access;
    }
    
    public void setAccess(boolean access) {
        this.access = access;
    }




}


